version: "2"

services:
  neo4j: 
    image: neo4j:latest
    environment: 
      - NEO4J_AUTH=neo4j/process.env.NEO4J_PASS
    volumes:
      - "c:/Users/services/instagram/data:/data"
    ports:
      - "7474:7474"
      - "7687:7687"

  nodeapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodeapp
    ports:
      - "4000:4000"
      - "5000:5000"
    volumes:
      - "c:/Users/services/instagram:/opt/app"